### ISSUE TITLE
Request for support for unset variable 

### ISSUE THREAD

**Issue by abdelmonem17** [coreos/envsubst-rs#15]
could you support set default value for unset envs in form of ${ENV_VAR:-defaultvalue} ?

**Comment by lucab** [comment]
Thanks for the report. The answer is no, this library scope is pretty small on purpose and just tries to mimic the basic features of <https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html>.
If your usecase ends up needing more advanced features (like this bash-style default), I'd recommend switching to a proper fully-fledged templating library.
