### ISSUE TITLE
Error: Custom { kind: Other, error: "Variable substitution failed: envsubst error: variable value '{\"locale\":\"en-us\",\"osLocale\":\"en-us\",\"availableLanguages\":{},\"_languagePackSupport\":true}' contains forbidden character '{'" }

### ISSUE THREAD

**Issue by davehorner** [coreos/envsubst-rs#26]
Hello,

I am working through this issue with svix-bridge.
https://github.com/svix/svix-webhooks/issues/1084

It looks like vscode has a variable with {} in it.

Error happening in envsubst substitute.
```
pub fn substitute<T>(template: T, variables: &HashMap<String, String>) -> Result<String, Error>
where
    T: Into<String>,
{
    let mut output = template.into();
    if variables.is_empty() {
        return Ok(output);
    }

    for (k, v) in variables {
        validate(k, "key")?;
        validate(v, "value")?;

        let from = format!("${{{}}}", k);
        output = output.replace(&from, &v)
    }

    Ok(output)
}
```

The value that is causing it to go mad when under debug in vscode is:
```
k="VSCODE_NLS_CONFIG"
v="{"locale":"en-us","osLocale":"en-us","availableLanguages":{},"_languagePackSupport":true}"
```
this value is not present in my system when I list variables via set in vscode terminal. 

The value being substituted must be free of { characters?

Thanks!

**Comment by lucab** [comment]
Thanks for the report.
From https://docs.rs/envsubst/latest/envsubst/fn.validate_vars.html:
> In order to make substitution deterministic, the following characters are not allowed within variables names nor values: `$`, `{`, `}`.

**Comment by davehorner** [comment]
I see.  I'm not sure how to proceed given I'm not in control of the environment variable's creation.  No chance of another interface that does allow substitution of values with special characters?

If not, I suppose the only thing to do is filter the bad variables from the environment.  Not sure what other remedies svix-bridge could do to support people with special characters in the environment.
